import type { MockSku, SellWindow } from "./types";

export const PROTOTYPE_CATEGORIES = [
  "Christmas",
  "Fall",
  "Spring",
  "Ornaments",
  "Garlands",
] as const;

export const PROTOTYPE_SUPPLIERS = [
  { id: "sup-hf", name: "HF Factory" },
  { id: "sup-jy", name: "JY Crafts" },
  { id: "sup-xd", name: "XD Drops (dropped)" },
] as const;

const iso = (year: number, month: number, day: number) =>
  new Date(year, month - 1, day).toISOString();

export const INITIAL_SKUS: MockSku[] = [
  {
    sku: "DC1001GN",
    name: "10\" Berry Stem - Green",
    supplierName: "HF Factory",
    supplierId: "sup-hf",
    categories: ["Christmas", "Garlands"],
    inactive: false,
    discontinued: false,
    onHand: 0,
    onOrder: 0,
    stickyLocked: true,
    windowIds: ["win-xmas-2025"],
  },
  {
    sku: "DC1002RD",
    name: "10\" Berry Stem - Red",
    supplierName: "HF Factory",
    supplierId: "sup-hf",
    categories: ["Christmas"],
    inactive: false,
    discontinued: false,
    onHand: 120,
    onOrder: 0,
    stickyLocked: false,
    windowIds: ["win-spring-2026"],
  },
  {
    sku: "DC2001GL",
    name: "Glass Ornament Ball",
    supplierName: "JY Crafts",
    supplierId: "sup-jy",
    categories: ["Christmas", "Ornaments"],
    inactive: false,
    discontinued: false,
    onHand: 0,
    onOrder: 480,
    stickyLocked: true,
    windowIds: [],
  },
  {
    sku: "DC2002GL",
    name: "Mercury Ornament Set",
    supplierName: "JY Crafts",
    supplierId: "sup-jy",
    categories: ["Christmas", "Ornaments"],
    inactive: false,
    discontinued: false,
    onHand: 0,
    onOrder: 0,
    stickyLocked: true,
    windowIds: [],
  },
  {
    sku: "DC3001OR",
    name: "Pumpkin Pick - Orange",
    supplierName: "HF Factory",
    supplierId: "sup-hf",
    categories: ["Fall"],
    inactive: false,
    discontinued: false,
    onHand: 44,
    onOrder: 0,
    stickyLocked: false,
    windowIds: ["win-spring-2026"],
  },
  {
    sku: "DC4001XX",
    name: "Dropped Factory Wreath",
    supplierName: "XD Drops (dropped)",
    supplierId: "sup-xd",
    categories: ["Christmas"],
    inactive: true,
    discontinued: false,
    onHand: 12,
    onOrder: 0,
    stickyLocked: true,
    windowIds: [],
  },
  {
    sku: "DC5001WH",
    name: "Pearl Spray - White",
    supplierName: "JY Crafts",
    supplierId: "sup-jy",
    categories: ["Christmas", "Garlands"],
    inactive: false,
    discontinued: true,
    onHand: 0,
    onOrder: 0,
    stickyLocked: true,
    windowIds: [],
  },
  {
    sku: "DC6001GN",
    name: "Mini Pine Garland",
    supplierName: "HF Factory",
    supplierId: "sup-hf",
    categories: ["Christmas", "Garlands", "Spring"],
    inactive: false,
    discontinued: false,
    onHand: 0,
    onOrder: 0,
    stickyLocked: true,
    windowIds: ["win-xmas-2025", "win-spring-2026"],
  },
];

export const INITIAL_WINDOWS: SellWindow[] = [
  {
    id: "win-xmas-2025",
    name: "Christmas 2025",
    categories: ["Christmas"],
    excludeSuppliers: ["sup-xd"],
    opensAt: iso(2025, 7, 1),
    closesAt: iso(2026, 1, 15),
    status: "closed",
    skuIds: ["DC1001GN", "DC6001GN"],
    appliedAt: iso(2025, 6, 15),
    appliedBy: "David Smith",
    manuallyClosedAt: null,
  },
  {
    id: "win-xmas-2026",
    name: "Christmas 2026",
    categories: ["Christmas"],
    excludeSuppliers: ["sup-xd"],
    opensAt: iso(2026, 7, 1),
    closesAt: iso(2027, 1, 15),
    status: "scheduled",
    skuIds: [],
    appliedAt: iso(2026, 6, 1),
    appliedBy: "David Smith",
    manuallyClosedAt: null,
  },
  {
    id: "win-spring-2026",
    name: "Spring 2026",
    categories: ["Spring"],
    excludeSuppliers: [],
    opensAt: iso(2026, 2, 1),
    closesAt: iso(2026, 5, 31),
    status: "open",
    skuIds: ["DC1002RD", "DC3001OR", "DC6001GN"],
    appliedAt: iso(2026, 1, 20),
    appliedBy: "David Smith",
    manuallyClosedAt: null,
  },
];
