import { PHASE1_PRODUCTS } from "../phase1-fixture.js";
import { DEMO_NAMED_CUSTOMERS } from "../reconciliation/expectations.js";

export const RESERVED_PRODUCT_NAMES = new Set([
  ...PHASE1_PRODUCTS.map((row) => row.name),
]);

export const RESERVED_SUPPLIER_NAMES = new Set(["Demo Supplier"]);

export const RESERVED_CUSTOMER_NAMES = new Set<string>([
  ...Object.values(DEMO_NAMED_CUSTOMERS).map((row) => row.name),
]);

export const PRODUCT_ADJECTIVES = [
  "Grade 5",
  "Grade 8",
  "Galvanized",
  "Stainless",
  "Zinc",
  "Coarse",
  "Fine",
  "Heavy",
  "Light",
  "Structural",
  "Machine",
  "Flange",
  "Socket",
  "Carriage",
  "Lag",
  "Toggle",
  "Anchor",
  "Threaded",
  "Metric",
  "Imperial",
  "Black oxide",
  "Hot-dip",
  "Nylon",
  "Steel",
  "Alloy",
  "Brass",
  "Copper",
  "Silicon",
  "Hardened",
  "Low profile",
  "Oversized",
  "Mini",
  "Long",
  "Short",
  "Wide",
  "Narrow",
  "Flat",
  "Round",
  "Square",
  "Hex",
  "Phillips",
  "Slotted",
  "Torx",
  "Self-drilling",
  "Self-tapping",
  "Collated",
  "Bulk",
  "Packaged",
  "Industrial",
  "Marine",
  "Deck",
  "Roofing",
  "Concrete",
  "Wood",
  "Panel",
  "Trim",
  "Cabinet",
  "Furniture",
  "Automotive",
  "Farm",
  "Rail",
  "Bridge",
  "Tower",
  "Utility",
  "Commercial",
  "Contractor",
  "OEM",
  "Retail",
  "Wholesale",
  "Premium",
  "Economy",
  "Standard",
  "Custom",
  "Universal",
  "Replacement",
  "Oversize",
  "Undersize",
  "Left-hand",
  "Right-hand",
  "Dual",
  "Single",
  "Double",
  "Triple",
  "Quad",
  "Multi",
  "Composite",
  "Hybrid",
  "Coated",
  "Uncoated",
  "Polished",
  "Matte",
  "Bright",
  "Plain",
  "Knurled",
  "Serrated",
  "Smooth",
  "Ribbed",
  "Grooved",
  "Slotted",
  "Keyed",
  "Locking",
  "Non-locking",
  "Removable",
  "Permanent",
  "Adjustable",
  "Fixed",
  "Swivel",
  "Rigid",
  "Flexible",
  "Corrosion-resistant",
  "Weatherproof",
  "Indoor",
  "Outdoor",
  "High-temp",
  "Low-temp",
  "Vibration-resistant",
  "Tamper-resistant",
  "Security",
  "Tamper-proof",
  "Breakaway",
  "Shear",
  "Blind",
  "Through",
  "Surface",
  "Subfloor",
  "Drywall",
  "Masonry",
  "Metal",
  "Plastic",
  "Composite",
  "Ceramic",
  "Glass",
  "Rubber",
  "Neoprene",
  "EPDM",
  "Viton",
  "Silicone",
  "Nylon insert",
  "All-metal",
  "Prevailing torque",
  "Non-metallic",
  "Metallic",
  "Electroplated",
  "Passivated",
  "Anodized",
  "Powder-coated",
  "Painted",
  "Raw",
  "Finished",
  "Partially threaded",
  "Fully threaded",
  "Shoulder",
  "Coupling",
  "Connecting",
  "Joining",
  "Fastening",
  "Anchoring",
  "Clamping",
  "Retaining",
  "Spacing",
  "Leveling",
  "Shimming",
  "Bushing",
  "Spacer",
  "Standoff",
  "Pin",
  "Clip",
  "Ring",
  "Hook",
  "Eye",
  "Turnbuckle",
  "Rod",
  "Stud",
  "Bolt",
  "Screw",
  "Nut",
  "Washer",
  "Anchor",
  "Rivet",
  "Staple",
  "Nail",
  "Pin",
  "Dowel",
  "Insert",
  "Plug",
  "Cap",
  "Cover",
  "Guard",
  "Shield",
  "Plate",
  "Bracket",
  "Mount",
  "Hanger",
  "Tie",
  "Strap",
  "Band",
  "Clamp",
  "Clip",
  "Retainer",
  "Latch",
  "Catch",
  "Stop",
  "Bumper",
  "Grommet",
  "Bushing",
  "Sleeve",
  "Collar",
  "Hub",
  "Flange",
  "Coupling",
  "Adapter",
  "Reducer",
  "Expander",
  "Union",
  "Elbow",
  "Tee",
  "Cross",
  "Wye",
  "Branch",
  "Connector",
  "Terminal",
  "Terminal block",
  "Ground",
  "Bonding",
  "Grounding",
  "Bonding strap",
  "Ground strap",
  "Ground rod",
  "Ground clip",
  "Ground bushing",
  "Ground lug",
  "Ground plate",
  "Ground bar",
  "Ground stud",
  "Ground screw",
  "Ground bolt",
  "Ground nut",
  "Ground washer",
  "Ground anchor",
  "Ground clamp",
  "Ground connector",
  "Ground terminal",
  "Ground terminal block",
  "Ground terminal lug",
  "Ground terminal plate",
  "Ground terminal bar",
  "Ground terminal stud",
  "Ground terminal screw",
  "Ground terminal bolt",
  "Ground terminal nut",
  "Ground terminal washer",
  "Ground terminal anchor",
  "Ground terminal clamp",
  "Ground terminal connector",
] as const;

export const PRODUCT_NOUNS = [
  "hex cap",
  "hex bolt",
  "carriage bolt",
  "lag bolt",
  "machine screw",
  "sheet metal screw",
  "wood screw",
  "deck screw",
  "self-tapping screw",
  "set screw",
  "shoulder bolt",
  "stud",
  "threaded rod",
  "coupling nut",
  "hex nut",
  "lock nut",
  "flange nut",
  "wing nut",
  "cap nut",
  "jam nut",
  "flat washer",
  "fender washer",
  "lock washer",
  "split washer",
  "wave washer",
  "finishing washer",
  "structural washer",
  "beveled washer",
  "square washer",
  "O-ring",
  " retaining ring",
  "snap ring",
  "E-clip",
  "C-clip",
  "D-ring",
  "eye bolt",
  "eye lag",
  "J-bolt",
  "U-bolt",
  "anchor bolt",
  "wedge anchor",
  "drop-in anchor",
  " sleeve anchor",
  "toggle bolt",
  "molly bolt",
  "concrete screw",
  "masonry nail",
  "roofing nail",
  "finish nail",
  "common nail",
  "box nail",
  "duplex nail",
  "ring shank nail",
  "spiral shank nail",
  "clip",
  "bracket",
  "hanger",
  "strap tie",
  "joist hanger",
  "post anchor",
  "deck clip",
  "rail clip",
  "panel clip",
  "cable clip",
  "pipe clamp",
  "hose clamp",
  "beam clamp",
  "conduit clamp",
  "ground clamp",
  "standoff",
  "spacer",
  "bushing",
  "grommet",
  "rivet",
  "blind rivet",
  "solid rivet",
  "pop rivet",
  "drive pin",
  "roll pin",
  "dowel pin",
  "clevis pin",
  "cotter pin",
  "hair pin",
  "spring pin",
  "taper pin",
  "groove pin",
  "slotted pin",
  "quick pin",
  " hitch pin",
  "lynch pin",
  "safety pin",
  "wire tie",
  "cable tie",
  "zip tie",
  "mounting plate",
  "base plate",
  "cover plate",
  "terminal",
  "terminal lug",
  "ground lug",
  "bonding strap",
  "ground strap",
  "thread insert",
  "helical insert",
  "press-fit insert",
  "heat-set insert",
  "ultrasonic insert",
  "molded insert",
  "threaded insert",
  "blind insert",
  "key-locking insert",
  "self-locking insert",
  "press nut",
  "clip nut",
  "weld nut",
  " cage nut",
  "T-nut",
  "pronged T-nut",
  "barrel nut",
  "cross dowel",
  "connector bolt",
  "sex bolt",
  "Chicago screw",
  "binding post",
  "thumb screw",
  "knurled knob",
  "hand knob",
  "star knob",
  "wing screw",
  "clamp knob",
  "leveling foot",
  "adjustable foot",
  "rubber bumper",
  "end cap",
  "tube cap",
  "pipe cap",
  "thread protector",
  "thread cap",
  "thread plug",
  "pipe plug",
  "flush plug",
  "snap plug",
  "hole plug",
  "panel plug",
  "blanking plug",
  "vent plug",
  "drain plug",
  "oil plug",
  "freeze plug",
  "expansion plug",
  "core plug",
  "welch plug",
  "cup plug",
  "hex plug",
  "square plug",
  "round plug",
  "slotted plug",
  "socket plug",
  "Allen plug",
  "Torx plug",
  "Phillips plug",
  "Slotted plug",
  "Tamper plug",
  "Security plug",
  "Breakaway plug",
  "Shear plug",
  "Blind plug",
  "Through plug",
  "Surface plug",
  "Subfloor plug",
  "Drywall plug",
  "Masonry plug",
  "Metal plug",
  "Plastic plug",
  "Composite plug",
  "Ceramic plug",
  "Glass plug",
  "Rubber plug",
  "Neoprene plug",
  "EPDM plug",
  "Viton plug",
  "Silicone plug",
  "Nylon plug",
  "All-metal plug",
  "Prevailing torque plug",
  "Non-metallic plug",
  "Metallic plug",
  "Electroplated plug",
  "Passivated plug",
  "Anodized plug",
  "Powder-coated plug",
  "Painted plug",
  "Raw plug",
  "Finished plug",
  "Partially threaded plug",
  "Fully threaded plug",
  "Shoulder plug",
  "Coupling plug",
  "Connecting plug",
  "Joining plug",
  "Fastening plug",
  "Anchoring plug",
  "Clamping plug",
  "Retaining plug",
  "Spacing plug",
  "Leveling plug",
  "Shimming plug",
  "Bushing plug",
  "Spacer plug",
  "Standoff plug",
  "Pin plug",
  "Clip plug",
  "Ring plug",
  "Hook plug",
  "Eye plug",
  "Turnbuckle plug",
  "Rod plug",
  "Stud plug",
  "Bolt plug",
  "Screw plug",
  "Nut plug",
  "Washer plug",
  "Anchor plug",
  "Rivet plug",
  "Staple plug",
  "Nail plug",
  "Pin plug",
  "Dowel plug",
  "Insert plug",
  "Cap plug",
  "Cover plug",
  "Guard plug",
  "Shield plug",
  "Plate plug",
  "Bracket plug",
  "Mount plug",
  "Hanger plug",
  "Tie plug",
  "Strap plug",
  "Band plug",
  "Clamp plug",
  "Clip plug",
  "Retainer plug",
  "Latch plug",
  "Catch plug",
  "Stop plug",
  "Bumper plug",
  "Grommet plug",
  "Bushing plug",
  "Sleeve plug",
  "Collar plug",
  "Hub plug",
  "Flange plug",
  "Coupling plug",
  "Adapter plug",
  "Reducer plug",
  "Expander plug",
  "Union plug",
  "Elbow plug",
  "Tee plug",
  "Cross plug",
  "Wye plug",
  "Branch plug",
  "Connector plug",
  "Terminal plug",
  "Terminal block plug",
  "Ground plug",
  "Bonding plug",
  "Grounding plug",
  "Bonding strap plug",
  "Ground strap plug",
  "Ground rod plug",
  "Ground clip plug",
  "Ground bushing plug",
  "Ground lug plug",
  "Ground plate plug",
  "Ground bar plug",
  "Ground stud plug",
  "Ground screw plug",
  "Ground bolt plug",
  "Ground nut plug",
  "Ground washer plug",
  "Ground anchor plug",
  "Ground clamp plug",
  "Ground connector plug",
  "Ground terminal plug",
  "Ground terminal block plug",
  "Ground terminal lug plug",
  "Ground terminal plate plug",
  "Ground terminal bar plug",
  "Ground terminal stud plug",
  "Ground terminal screw plug",
  "Ground terminal bolt plug",
  "Ground terminal nut plug",
  "Ground terminal washer plug",
  "Ground terminal anchor plug",
  "Ground terminal clamp plug",
  "Ground terminal connector plug",
] as const;

export const SUPPLIER_MILL_SUFFIXES = [
  "Northern mill",
  "Summit mill",
  "River mill",
  "Prairie mill",
  "Lake mill",
  "Valley mill",
  "Mountain mill",
  "Coastal mill",
  "Harbor mill",
  "Ridge mill",
  "Canyon mill",
  "Meadow mill",
  "Timber mill",
  "Granite mill",
  "Copper mill",
  "Steel mill",
  "Iron mill",
  "Alloy mill",
  "Foundry mill",
  "Forge mill",
  "Works mill",
  "Supply mill",
  "Fastener mill",
  "Bolt mill",
  "Nut mill",
] as const;

export const MIX_CUSTOMER_TRADE_WORDS = [
  "Lakeside",
  "Prairie",
  "Summit",
  "River",
  "Valley",
  "Mountain",
  "Coastal",
  "Harbor",
  "Ridge",
  "Canyon",
  "Meadow",
  "Timber",
  "Granite",
  "Copper",
  "Steel",
  "Iron",
  "Alloy",
  "Northern",
  "Southern",
  "Eastern",
  "Western",
  "Central",
  "Metro",
  "Urban",
  "Rural",
  "Frontier",
  "Pioneer",
  "Heritage",
  "Liberty",
  "Union",
  "Anchor",
  "Beacon",
  "Bridge",
  "Cedar",
  "Oak",
  "Pine",
  "Maple",
  "Birch",
  "Spruce",
  "Aspen",
  "Willow",
  "Elm",
  "Ash",
  "Hickory",
  "Redwood",
  "Sequoia",
  "Sierra",
  "Cascade",
  "Pacific",
  "Atlantic",
  "Gulf",
  "Prairie",
  "Desert",
  "Mesa",
  "Butte",
  "Bluff",
  "Creek",
  "Brook",
  "Spring",
  "Falls",
  "Rapids",
  "Bay",
  "Cove",
  "Point",
  "Shore",
  "Dock",
  "Pier",
  "Wharf",
  "Yard",
  "Depot",
  "Terminal",
  "Junction",
  "Crossing",
  "Station",
  "Exchange",
  "Market",
  "Trade",
  "Supply",
  "Source",
  "Outlet",
  "Center",
  "Hub",
  "Works",
  "Forge",
  "Foundry",
  "Mill",
  "Shop",
  "Store",
  "Mart",
  "House",
  "Co",
  "Partners",
  "Group",
  "Brothers",
  "Sons",
  "Daughters",
  "Family",
  "Industrial",
  "Commercial",
  "Wholesale",
  "Distribution",
  "Distributors",
  "Fasteners",
  "Hardware",
  "Bolt",
  "Nut",
  "Screw",
  "Anchor",
  "Tool",
  "Parts",
  "Components",
  "Assembly",
  "Fabrication",
  "Manufacturing",
  "Processing",
  "Packaging",
  "Logistics",
  "Transport",
  "Freight",
  "Cargo",
  "Carrier",
  "Express",
  "Direct",
  "Premier",
  "Select",
  "Choice",
  "Quality",
  "Value",
  "Economy",
  "Budget",
  "Discount",
  "Bargain",
  "Deal",
  "Save",
  "Smart",
  "Pro",
  "Expert",
  "Master",
  "Elite",
  "Prime",
  "Gold",
  "Silver",
  "Bronze",
  "Platinum",
  "Diamond",
  "Crystal",
  "Pearl",
  "Ruby",
  "Sapphire",
  "Emerald",
  "Topaz",
  "Onyx",
  "Jade",
  "Amber",
  "Coral",
  "Ivory",
  "Ebony",
  "Mahogany",
  "Walnut",
  "Cherry",
  "Teak",
  "Bamboo",
  "Rattan",
  "Wicker",
  "Canvas",
  "Denim",
  "Leather",
  "Suede",
  "Wool",
  "Cotton",
  "Linen",
  "Silk",
  "Velvet",
  "Satin",
  "Tweed",
  "Flannel",
  "Fleece",
  "Nylon",
  "Polyester",
  "Acrylic",
  "Rayon",
  "Spandex",
  "Kevlar",
  "Carbon",
  "Fiberglass",
  "Graphite",
  "Titanium",
  "Aluminum",
  "Magnesium",
  "Zinc",
  "Brass",
  "Bronze",
  "Nickel",
  "Chrome",
  "Cobalt",
  "Tungsten",
  "Molybdenum",
  "Vanadium",
  "Manganese",
  "Silicon",
  "Germanium",
  "Gallium",
  "Indium",
  "Tin",
  "Lead",
  "Mercury",
  "Bismuth",
  "Antimony",
  "Arsenic",
  "Selenium",
  "Tellurium",
  "Polonium",
  "Astatine",
  "Radon",
  "Francium",
  "Radium",
  "Actinium",
  "Thorium",
  "Protactinium",
  "Uranium",
  "Neptunium",
  "Plutonium",
  "Americium",
  "Curium",
  "Berkelium",
  "Californium",
  "Einsteinium",
  "Fermium",
  "Mendelevium",
  "Nobelium",
  "Lawrencium",
  "Rutherfordium",
  "Dubnium",
  "Seaborgium",
  "Bohrium",
  "Hassium",
  "Meitnerium",
  "Darmstadtium",
  "Roentgenium",
  "Copernicium",
  "Nihonium",
  "Flerovium",
  "Moscovium",
  "Livermorium",
  "Tennessine",
  "Oganesson",
] as const;

export const MIX_CUSTOMER_TRADE_TYPES = [
  "Hardware Co.",
  "Fastener Supply",
  "Industrial Supply",
  "Bolt & Nut Co.",
  "Distribution",
  "Wholesale",
  "Trading Co.",
  "Supply Co.",
  "Parts Co.",
  "Components Inc.",
  "Manufacturing",
  "Fabricators",
  "Works",
  "Foundry",
  "Forge",
  "Mill",
  "Depot",
  "Outlet",
  "Center",
  "Hub",
  "Partners",
  "Group",
  "Brothers",
  "Sons",
  "Distributors",
  "Logistics",
  "Freight",
  "Express",
  "Direct",
  "Premier",
  "Select",
  "Choice",
  "Quality",
  "Value",
  "Economy",
  "Budget",
  "Discount",
  "Bargain",
  "Deal",
  "Save",
  "Smart",
  "Pro",
  "Expert",
  "Master",
  "Elite",
  "Prime",
  "Gold",
  "Silver",
  "Bronze",
  "Platinum",
  "Diamond",
  "Crystal",
  "Pearl",
  "Ruby",
  "Sapphire",
  "Emerald",
  "Topaz",
  "Onyx",
  "Jade",
  "Amber",
  "Coral",
  "Ivory",
  "Ebony",
  "Mahogany",
  "Walnut",
  "Cherry",
  "Teak",
  "Bamboo",
  "Rattan",
  "Wicker",
  "Canvas",
  "Denim",
  "Leather",
  "Suede",
  "Wool",
  "Cotton",
  "Linen",
  "Silk",
  "Velvet",
  "Satin",
  "Tweed",
  "Flannel",
  "Fleece",
  "Nylon",
  "Polyester",
  "Acrylic",
  "Rayon",
  "Spandex",
  "Kevlar",
  "Carbon",
  "Fiberglass",
  "Graphite",
  "Titanium",
  "Aluminum",
  "Magnesium",
  "Zinc",
  "Brass",
  "Bronze",
  "Nickel",
  "Chrome",
  "Cobalt",
  "Tungsten",
  "Molybdenum",
  "Vanadium",
  "Manganese",
  "Silicon",
] as const;

export const MIX_ADDRESS_STREETS = [
  "Cedar St",
  "Pine Ave",
  "Oak Blvd",
  "Maple Dr",
  "Elm Way",
  "Birch Ln",
  "Spruce Rd",
  "Aspen Ct",
  "Willow Pl",
  "Ash Ter",
  "Hickory Cir",
  "Walnut St",
  "Cherry Ave",
  "Teak Blvd",
  "Bamboo Dr",
  "Industrial Pkwy",
  "Commerce Dr",
  "Trade Center Rd",
  "Warehouse Blvd",
  "Distribution Way",
  "Supply Chain Ln",
  "Logistics Dr",
  "Freight Ave",
  "Cargo Rd",
  "Terminal Blvd",
  "Depot St",
  "Junction Rd",
  "Crossing Ave",
  "Station Blvd",
  "Exchange Dr",
  "Market St",
  "Outlet Rd",
  "Center Ave",
  "Hub Blvd",
  "Works Dr",
  "Forge Ln",
  "Foundry Rd",
  "Mill Ave",
  "Shop St",
  "Store Blvd",
  "Mart Dr",
  "House Rd",
  "Co Ave",
  "Partners Blvd",
  "Group Dr",
  "Brothers Ln",
  "Sons Rd",
  "Daughters Ave",
  "Family St",
  "Industrial Blvd",
  "Commercial Dr",
  "Wholesale Ave",
  "Distribution Rd",
  "Distributors Blvd",
  "Fasteners Dr",
  "Hardware Ln",
  "Bolt Ave",
  "Nut Rd",
  "Screw Blvd",
  "Anchor Dr",
  "Tool St",
  "Parts Ave",
  "Components Rd",
  "Assembly Blvd",
  "Fabrication Dr",
  "Manufacturing Ln",
  "Processing Rd",
  "Packaging Ave",
  "Logistics Blvd",
  "Transport Dr",
  "Freight Ln",
  "Cargo Ave",
  "Carrier Rd",
  "Express Blvd",
  "Direct Dr",
  "Premier Ln",
  "Select Ave",
  "Choice Rd",
  "Quality Blvd",
  "Value Dr",
  "Economy Ln",
  "Budget Ave",
  "Discount Rd",
  "Bargain Blvd",
  "Deal Dr",
  "Save Ln",
  "Smart Ave",
  "Pro Rd",
  "Expert Blvd",
  "Master Dr",
  "Elite Ln",
  "Prime Ave",
  "Gold Rd",
  "Silver Blvd",
  "Bronze Dr",
  "Platinum Ln",
  "Diamond Ave",
  "Crystal Rd",
  "Pearl Blvd",
  "Ruby Dr",
  "Sapphire Ln",
  "Emerald Ave",
  "Topaz Rd",
  "Onyx Blvd",
  "Jade Dr",
  "Amber Ln",
  "Coral Ave",
  "Ivory Rd",
  "Ebony Blvd",
  "Mahogany Dr",
  "Walnut Ln",
  "Cherry Ave",
  "Teak Rd",
  "Bamboo Blvd",
  "Rattan Dr",
  "Wicker Ln",
  "Canvas Ave",
  "Denim Rd",
  "Leather Blvd",
  "Suede Dr",
  "Wool Ln",
  "Cotton Ave",
  "Linen Rd",
  "Silk Blvd",
  "Velvet Dr",
  "Satin Ln",
  "Tweed Ave",
  "Flannel Rd",
  "Fleece Blvd",
  "Nylon Dr",
  "Polyester Ln",
  "Acrylic Ave",
  "Rayon Rd",
  "Spandex Blvd",
  "Kevlar Dr",
  "Carbon Ln",
  "Fiberglass Ave",
  "Graphite Rd",
  "Titanium Blvd",
  "Aluminum Dr",
  "Magnesium Ln",
  "Zinc Ave",
  "Brass Rd",
  "Bronze Blvd",
  "Nickel Dr",
  "Chrome Ln",
  "Cobalt Ave",
  "Tungsten Rd",
  "Molybdenum Blvd",
  "Vanadium Dr",
  "Manganese Ln",
  "Silicon Ave",
] as const;

export const MIX_ADDRESS_CITIES = [
  { city: "Boise", region: "ID", postal: "83702" },
  { city: "Denver", region: "CO", postal: "80202" },
  { city: "Salt Lake City", region: "UT", postal: "84101" },
  { city: "Phoenix", region: "AZ", postal: "85001" },
  { city: "Albuquerque", region: "NM", postal: "87101" },
  { city: "Las Vegas", region: "NV", postal: "89101" },
  { city: "Portland", region: "OR", postal: "97201" },
  { city: "Seattle", region: "WA", postal: "98101" },
  { city: "Spokane", region: "WA", postal: "99201" },
  { city: "Billings", region: "MT", postal: "59101" },
  { city: "Cheyenne", region: "WY", postal: "82001" },
  { city: "Fargo", region: "ND", postal: "58102" },
  { city: "Sioux Falls", region: "SD", postal: "57104" },
  { city: "Omaha", region: "NE", postal: "68102" },
  { city: "Des Moines", region: "IA", postal: "50309" },
  { city: "Kansas City", region: "MO", postal: "64106" },
  { city: "Wichita", region: "KS", postal: "67202" },
  { city: "Oklahoma City", region: "OK", postal: "73102" },
  { city: "Little Rock", region: "AR", postal: "72201" },
  { city: "Memphis", region: "TN", postal: "38103" },
  { city: "Nashville", region: "TN", postal: "37201" },
  { city: "Louisville", region: "KY", postal: "40202" },
  { city: "Indianapolis", region: "IN", postal: "46204" },
  { city: "Columbus", region: "OH", postal: "43215" },
  { city: "Detroit", region: "MI", postal: "48226" },
  { city: "Milwaukee", region: "WI", postal: "53202" },
  { city: "Minneapolis", region: "MN", postal: "55401" },
  { city: "Des Moines", region: "IA", postal: "50309" },
  { city: "St. Louis", region: "MO", postal: "63101" },
  { city: "Chicago", region: "IL", postal: "60601" },
  { city: "Cleveland", region: "OH", postal: "44114" },
  { city: "Pittsburgh", region: "PA", postal: "15222" },
  { city: "Buffalo", region: "NY", postal: "14202" },
  { city: "Boston", region: "MA", postal: "02108" },
  { city: "Hartford", region: "CT", postal: "06103" },
  { city: "Providence", region: "RI", postal: "02903" },
  { city: "Albany", region: "NY", postal: "12207" },
  { city: "Philadelphia", region: "PA", postal: "19107" },
  { city: "Baltimore", region: "MD", postal: "21201" },
  { city: "Richmond", region: "VA", postal: "23219" },
  { city: "Charlotte", region: "NC", postal: "28202" },
  { city: "Atlanta", region: "GA", postal: "30303" },
  { city: "Jacksonville", region: "FL", postal: "32202" },
  { city: "Miami", region: "FL", postal: "33130" },
  { city: "Tampa", region: "FL", postal: "33602" },
  { city: "Orlando", region: "FL", postal: "32801" },
  { city: "New Orleans", region: "LA", postal: "70112" },
  { city: "Houston", region: "TX", postal: "77002" },
  { city: "Dallas", region: "TX", postal: "75201" },
  { city: "Austin", region: "TX", postal: "78701" },
  { city: "San Antonio", region: "TX", postal: "78205" },
  { city: "El Paso", region: "TX", postal: "79901" },
  { city: "Tucson", region: "AZ", postal: "85701" },
  { city: "Sacramento", region: "CA", postal: "95814" },
  { city: "San Francisco", region: "CA", postal: "94102" },
  { city: "Los Angeles", region: "CA", postal: "90012" },
  { city: "San Diego", region: "CA", postal: "92101" },
  { city: "Fresno", region: "CA", postal: "93721" },
  { city: "Reno", region: "NV", postal: "89501" },
  { city: "Anchorage", region: "AK", postal: "99501" },
  { city: "Honolulu", region: "HI", postal: "96813" },
] as const;
